In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv(r"C:\Users\S\Downloads\Loan_CData.csv")

In [3]:
df

,Unnamed: 0,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [4]:
df.shape

(614, 13)

In [5]:
df.size

7982

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         614 non-null    int64
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(2), object(7)
memory usage: 62.5+ KB

In [7]:
df.columns

Index(['Unnamed: 0', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [8]:
df.head()

,Unnamed: 0,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [9]:
df.tail()

,Unnamed: 0,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [10]:
df.describe()

,Unnamed: 0,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000
mean,306.500000,5403.459283,1621.245798,145.752443,342.410423,0.855049
std,177.390811,6109.041673,2926.248369,84.107233,64.428629,0.352339
min,0.000000,150.000000,0.000000,9.000000,12.000000,0.000000
25%,153.250000,2877.500000,0.000000,100.250000,360.000000,1.000000
50%,306.500000,3812.500000,1188.500000,128.000000,360.000000,1.000000
75%,459.750000,5795.000000,2297.250000,164.750000,360.000000,1.000000
max,613.000000,81000.000000,41667.000000,700.000000,480.000000,1.000000

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

Unnamed: 0           0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [13]:
df.nunique()

Unnamed: 0           614
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
Loan_Status            2
dtype: int64

In [14]:
df.value_counts()

Unnamed: 0  Gender  Married  Dependents  Education     Self_Employed  ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  Property_Area  Loan_Status
0           Male    No       0           Graduate      No             5849             0.0                128.0       360.0             1.0             Urban          Y              1
412         Male    Yes      0           Not Graduate  No             6096             0.0                218.0       360.0             0.0             Rural          N              1
405         Female  No       0           Graduate      No             4547             0.0                115.0       360.0             1.0             Semiurban      Y              1
406         Male    Yes      0           Not Graduate  No             2167             2400.0             115.0       360.0             1.0             Urban          Y              1
407         Female  No       0           Not Graduate  No             2213             0.0                66.0        360.0             1.0             Rural          Y              1
                                                                                                                                                                                     ..
205         Female  No       0           Not Graduate  No             4408             0.0                120.0       360.0             1.0             Semiurban      Y              1
206         Female  No       0           Graduate      No             3244             0.0                80.0        360.0             1.0             Urban          Y              1
207         Male    No       0           Not Graduate  No             3975             2531.0             55.0        360.0             1.0             Rural          Y              1
208         Male    No       0           Graduate      No             2479             0.0                59.0        360.0             1.0             Urban          Y              1
613         Female  No       0           Graduate      Yes            4583             0.0                133.0       360.0             0.0             Semiurban      N              1
Name: count, Length: 614, dtype: int64

In [15]:
df.drop(columns="Unnamed: 0",inplace=True)

In [16]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

## encoding

In [17]:
encoder=LabelEncoder()

In [18]:
encoder

LabelEncoder()

In [19]:
df["gender"]=encoder.fit_transform(df["Gender"])

In [20]:
df.drop(columns="Gender",inplace=True)

In [21]:
df

,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,gender
0,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,1
1,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,1
2,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,1
3,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,1
4,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,0
610,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,1
611,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,1
612,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,1
613,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,0

In [22]:
df["married"]=encoder.fit_transform(df["Married"])

In [23]:
df.drop(columns="Married",inplace=True)

In [24]:
df

,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,gender,married
0,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,1,0
1,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,1,1
2,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,1,1
3,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,1,1
4,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,0,0
610,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,1,1
611,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,1,1
612,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,1,1
613,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,0,0

In [25]:
df["dependents"]=encoder.fit_transform(df["Dependents"])

In [26]:
df.drop(columns="Dependents",inplace=True)

In [27]:
df

,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,gender,married,dependents
0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y,1,0,0
1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,1,1,1
2,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,1,1,0
3,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,1,1,0
4,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,0,0,0
610,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,1,1,3
611,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,1,1,1
612,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,1,1,2
613,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,0,0,0

In [28]:
df["education"]=encoder.fit_transform(df["Education"])

In [29]:
df.drop(columns="Education",inplace=True)

In [30]:
df

,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,gender,married,dependents,education
0,No,5849,0.0,128.0,360.0,1.0,Urban,Y,1,0,0,0
1,No,4583,1508.0,128.0,360.0,1.0,Rural,N,1,1,1,0
2,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,1,1,0,0
3,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,1,1,0,1
4,No,6000,0.0,141.0,360.0,1.0,Urban,Y,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
609,No,2900,0.0,71.0,360.0,1.0,Rural,Y,0,0,0,0
610,No,4106,0.0,40.0,180.0,1.0,Rural,Y,1,1,3,0
611,No,8072,240.0,253.0,360.0,1.0,Urban,Y,1,1,1,0
612,No,7583,0.0,187.0,360.0,1.0,Urban,Y,1,1,2,0
613,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,0,0,0,0

In [31]:
df["selfemployed"]=encoder.fit_transform(df["Self_Employed"])

In [32]:
df.drop(columns="Self_Employed",inplace=True)

In [33]:
df

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,gender,married,dependents,education,selfemployed
0,5849,0.0,128.0,360.0,1.0,Urban,Y,1,0,0,0,0
1,4583,1508.0,128.0,360.0,1.0,Rural,N,1,1,1,0,0
2,3000,0.0,66.0,360.0,1.0,Urban,Y,1,1,0,0,1
3,2583,2358.0,120.0,360.0,1.0,Urban,Y,1,1,0,1,0
4,6000,0.0,141.0,360.0,1.0,Urban,Y,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
609,2900,0.0,71.0,360.0,1.0,Rural,Y,0,0,0,0,0
610,4106,0.0,40.0,180.0,1.0,Rural,Y,1,1,3,0,0
611,8072,240.0,253.0,360.0,1.0,Urban,Y,1,1,1,0,0
612,7583,0.0,187.0,360.0,1.0,Urban,Y,1,1,2,0,0
613,4583,0.0,133.0,360.0,0.0,Semiurban,N,0,0,0,0,1

In [34]:
df["propertyarea"]=encoder.fit_transform(df["Property_Area"])

In [35]:
df.drop(columns="Property_Area",inplace=True)

In [36]:
df

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender,married,dependents,education,selfemployed,propertyarea
0,5849,0.0,128.0,360.0,1.0,Y,1,0,0,0,0,2
1,4583,1508.0,128.0,360.0,1.0,N,1,1,1,0,0,0
2,3000,0.0,66.0,360.0,1.0,Y,1,1,0,0,1,2
3,2583,2358.0,120.0,360.0,1.0,Y,1,1,0,1,0,2
4,6000,0.0,141.0,360.0,1.0,Y,1,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
609,2900,0.0,71.0,360.0,1.0,Y,0,0,0,0,0,0
610,4106,0.0,40.0,180.0,1.0,Y,1,1,3,0,0,0
611,8072,240.0,253.0,360.0,1.0,Y,1,1,1,0,0,2
612,7583,0.0,187.0,360.0,1.0,Y,1,1,2,0,0,2
613,4583,0.0,133.0,360.0,0.0,N,0,0,0,0,1,1

In [37]:
df["loanstatus"]=encoder.fit_transform(df["Loan_Status"])

In [40]:
df.drop(columns="Loan_Status",inplace=True)

In [41]:
df

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,gender,married,dependents,education,selfemployed,propertyarea,loanstatus
0,5849,0.0,128.0,360.0,1.0,1,0,0,0,0,2,1
1,4583,1508.0,128.0,360.0,1.0,1,1,1,0,0,0,0
2,3000,0.0,66.0,360.0,1.0,1,1,0,0,1,2,1
3,2583,2358.0,120.0,360.0,1.0,1,1,0,1,0,2,1
4,6000,0.0,141.0,360.0,1.0,1,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,2900,0.0,71.0,360.0,1.0,0,0,0,0,0,0,1
610,4106,0.0,40.0,180.0,1.0,1,1,3,0,0,0,1
611,8072,240.0,253.0,360.0,1.0,1,1,1,0,0,2,1
612,7583,0.0,187.0,360.0,1.0,1,1,2,0,0,2,1
613,4583,0.0,133.0,360.0,0.0,0,0,0,0,1,1,0