In [29]:
import pandas as pd 
df=pd.read_csv(r"C:\Users\S\Downloads\files (2)\files\employee_data.csv")

In [30]:
df

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

### Q1

In [31]:
df.head()

   ID         Name Department      City   Job Role   Salary  Exp_Yrs  Rating
0   1   Arun Kumar      Sales   Calicut  Executive  28000.0        3     4.2
1   2   Priya Nair         IT     Kochi  Developer  45000.0        5     4.7
2   3  Rahul Menon         HR   Calicut    Manager  38000.0        7     NaN
3   4    Sneha Das      Sales  Thrissur  Executive  29000.0        2     3.9
4   5      Vijay S         IT     Kochi  Developer  47000.0        6     4.5

### Q2

In [4]:
df.shape

(63, 8)

### Q3

In [5]:
df.columns

Index(['ID', 'Name', 'Department', 'City', 'Job Role', 'Salary', 'Exp_Yrs',
       'Rating'],
      dtype='object')

In [6]:
df.dtypes

ID              int64
Name           object
Department     object
City           object
Job Role       object
Salary        float64
Exp_Yrs         int64
Rating        float64
dtype: object

In [7]:
df.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

### Q4

In [8]:
df.describe()

              ID        Salary    Exp_Yrs     Rating
count  63.000000     62.000000  63.000000  58.000000
mean   32.000000  38822.580645   6.063492   4.194828
std    18.330303  12657.239480   3.267005   0.455925
min     1.000000  25000.000000   1.000000   3.400000
25%    16.500000  28000.000000   3.000000   3.800000
50%    32.000000  34000.000000   6.000000   4.200000
75%    47.500000  46500.000000   9.000000   4.600000
max    63.000000  65500.000000  12.000000   4.900000

In [9]:
df["Salary"].mean()

np.float64(38822.58064516129)

### Q5

In [10]:
df.size

504

### Q6

In [11]:
df["Department"].unique()

array(['Sales', 'IT', 'HR', 'Finance'], dtype=object)

In [12]:
df["Department"].nunique()

4

### Q7

In [13]:
df["Department"].value_counts()

Department
Sales      19
IT         19
HR         16
Finance     9
Name: count, dtype: int64

### Q8

In [14]:
df["City"].value_counts()

City
Calicut     18
Kochi       15
Thrissur    12
Palakkad     8
Kannur       4
Name: count, dtype: int64

### Q9

In [15]:
df["Job Role"].unique()

array(['Executive', 'Developer', 'Manager', 'Analyst', 'Lead',
       'Senior Analyst', 'Senior Executive', 'Recruiter', 'QA Engineer',
       'Senior Developer'], dtype=object)

### Q10

In [16]:
df[["Name","Department","Salary"]]

            Name Department   Salary
0     Arun Kumar      Sales  28000.0
1     Priya Nair         IT  45000.0
2    Rahul Menon         HR  38000.0
3      Sneha Das      Sales  29000.0
4        Vijay S         IT  47000.0
..           ...        ...      ...
58  Joseph Kumar    Finance  38500.0
59   Sreeja Devi    Finance  48000.0
60    Priya Nair         IT  45000.0
61       Anoop M         IT  43000.0
62   Jishnu Devi         HR  26000.0

[63 rows x 3 columns]

In [17]:
df[["Name","Department","Salary"]].describe(include="all")

              Name Department        Salary
count           58         63     62.000000
unique          49          4           NaN
top     Arun Kumar      Sales           NaN
freq             3         19           NaN
mean           NaN        NaN  38822.580645
std            NaN        NaN  12657.239480
min            NaN        NaN  25000.000000
25%            NaN        NaN  28000.000000
50%            NaN        NaN  34000.000000
75%            NaN        NaN  46500.000000
max            NaN        NaN  65500.000000

### Q11

In [18]:
df.isnull()

       ID   Name  Department   City  Job Role  Salary  Exp_Yrs  Rating
0   False  False       False  False     False   False    False   False
1   False  False       False  False     False   False    False   False
2   False  False       False  False     False   False    False    True
3   False  False       False  False     False   False    False   False
4   False  False       False  False     False   False    False   False
..    ...    ...         ...    ...       ...     ...      ...     ...
58  False  False       False  False     False   False    False   False
59  False  False       False  False     False   False    False   False
60  False  False       False  False     False   False    False   False
61  False  False       False  False     False   False    False   False
62  False  False       False  False     False   False    False   False

[63 rows x 8 columns]

In [19]:
df.isnull().sum()

ID            0
Name          5
Department    0
City          6
Job Role      0
Salary        1
Exp_Yrs       0
Rating        5
dtype: int64

### Q12

In [20]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
58    False
59    False
60    False
61    False
62    False
Length: 63, dtype: bool

In [21]:
df.duplicated().sum()

np.int64(0)

### Q13

In [22]:
df.drop_duplicates()

,ID,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,1,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,2,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
2,3,Rahul Menon,HR,Calicut,Manager,38000.0,7,NaN
3,4,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,5,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
...,...,...,...,...,...,...,...,...
58,59,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,60,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,61,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,62,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,63,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4

In [23]:
df.shape

(63, 8)

In [24]:
df.drop_duplicates(inplace=True)

In [25]:
df.shape

(63, 8)

### Q14

In [26]:
df.drop(columns="ID",inplace=True)

In [27]:
df.shape

(63, 7)

### Q15

In [28]:
df.dropna()

,Name,Department,City,Job Role,Salary,Exp_Yrs,Rating
0,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
1,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
3,Sneha Das,Sales,Thrissur,Executive,29000.0,2,3.9
4,Vijay S,IT,Kochi,Developer,47000.0,6,4.5
7,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
8,Divya R,HR,Thrissur,Executive,26000.0,1,3.5
10,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
12,Rajan T,Finance,Calicut,Senior Analyst,41000.0,6,4.0
15,Sreeja V,HR,Calicut,Executive,25000.0,1,3.8
17,Lakshmi G,Sales,Thrissur,Executive,27000.0,2,3.6
18,Arun Kumar,Sales,Calicut,Executive,28000.0,3,4.2
19,Jishnu C,IT,Kochi,Lead,65000.0,11,4.9
21,Jishnu M,Sales,Palakkad,Senior Executive,25000.0,9,3.7
22,Sreeja C,Sales,Thrissur,Manager,27000.0,4,4.8
23,Rahul Pillai,HR,Palakkad,Executive,36000.0,2,4.2
24,Rahul Devi,Sales,Kochi,Manager,26000.0,4,4.7
25,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4
27,Pradeep G,IT,Kannur,Lead,48000.0,3,3.8
28,Manoj M,Finance,Kochi,Manager,47500.0,2,4.5
30,Suresh Das,HR,Thrissur,Manager,29000.0,8,3.4
31,Vishnu Raj,Sales,Palakkad,Senior Executive,28000.0,3,4.0
32,Pradeep Kumar,HR,Calicut,Manager,33500.0,4,3.5
33,Bindu S,Sales,Kochi,Senior Executive,32500.0,9,3.6
34,Vishnu G,IT,Thrissur,QA Engineer,56500.0,8,3.6
36,Maya Thomas,IT,Kannur,Lead,65000.0,8,4.6
37,Sneha Devi,Finance,Calicut,Analyst,44500.0,12,3.9
38,Naveen K,Finance,Kannur,Analyst,34000.0,8,4.6
41,Sneha Nair,HR,Palakkad,Manager,29000.0,1,4.8
42,Ajay Das,IT,Palakkad,Lead,58500.0,10,3.5
43,Jishnu Devi,HR,Thrissur,Executive,32000.0,7,3.6
44,Sajith Mathew,Sales,Palakkad,Executive,26000.0,9,3.7
45,Nimisha R,HR,Kannur,Recruiter,33500.0,10,4.9
46,Fathima K,Sales,Calicut,Executive,33500.0,3,3.8
49,Sreekanth Krishnan,HR,Kochi,Manager,28000.0,1,3.9
50,Sanjay Devi,IT,Calicut,Senior Developer,64500.0,9,4.7
51,Naveen C,IT,Calicut,Lead,63500.0,6,4.6
52,Kiran G,IT,Calicut,QA Engineer,47000.0,4,4.6
53,Lakshmi G,Sales,Thrissur,Manager,26000.0,5,3.9
54,Anoop K,Sales,Kochi,Senior Executive,29000.0,1,3.6
55,Deepa Thomas,Sales,Kochi,Manager,25500.0,12,4.1
56,Manoj C,IT,Calicut,Senior Developer,59500.0,6,4.4
57,Ajay T,HR,Palakkad,Executive,30000.0,7,4.4
58,Joseph Kumar,Finance,Thrissur,Senior Analyst,38500.0,7,4.6
59,Sreeja Devi,Finance,Calicut,Senior Analyst,48000.0,11,4.3
60,Priya Nair,IT,Kochi,Developer,45000.0,5,4.7
61,Anoop M,IT,Calicut,Developer,43000.0,5,4.3
62,Jishnu Devi,HR,Thrissur,Recruiter,26000.0,10,4.4